# config.toml
baseURL = "https://example.org/"
languageCode = "en-us"
title = "Emily Tucker"
theme = "blog-theme"

# Enable Goldmark's attribute feature for custom styling (e.g. for newthought)
[markup.goldmark.renderer]
  unsafe = true # Set to true if you want to allow raw HTML in markdown for sidenotes/marginnotes
# [markup.goldmark.extensions]
#   attributes = true # Allows adding {#id .class} to markdown elements

[params]
  author = "Emily Tucker"
  description = "Emily Tucker - CS PhD student at Georgia Tech."
  marginNoteInd = "†"
  [params.socials]
    emailuser = "emily.tucker"
    emaildomain = "gatech.edu"
    github = "axolotls73"
    orcid = "0009-0002-1447-5683"
    google-scholar = "R1mztXQAAAAJ"
    ebird = "MjU2OTg5NQ"

# Pagination
# paginate = 3 # Number of posts per page on list pages

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.highlight]
  noClasses = false
